// download the paste json as code extension
// create empty typescipt file
// copy the json data from swagger
// Command + Shift + P => shortcut for searchingfor all the preferences

// Generated by https://quicktype.io

export interface MovieCard {
    id:          number;
    title:       string;
    posterUrl:   string;
    releaseDate: string;
}
